export default {
  FIRE_SNAP: 'FIRE_SNAP',
  REMOVE: 'REMOVE',
  SAVE: 'SAVE',
  CHANGE: 'CHANGE',
  TAKE_PICTURE: 'TAKE_PICTURE',
  TOGGLE_FLASH: 'TOGGLE_FLASH',
  TOGGLE_HIDE: 'TOGGLE_HIDE',
  TOGGLE_RATIO: 'TOGGLE_RATIO',
  DISABLE_SAVE: 'DISABLE_SAVE'
}
